#!/bin/bash
# ─── TeachHub Deployment Script ──────────────────────────
# Run on a fresh Ubuntu 22.04 Contabo VPS:
#   curl -sSL https://raw.githubusercontent.com/YOUR_USER/teachhub/main/deploy.sh | bash
#   OR
#   wget -qO- https://raw.githubusercontent.com/YOUR_USER/teachhub/main/deploy.sh | bash
#   OR just copy this file to the server and run: bash deploy.sh
#
# What this script does:
#   1. Installs Docker & Docker Compose
#   2. Configures firewall (HTTP, HTTPS, SSH, LiveKit UDP)
#   3. Generates secure random passwords
#   4. Creates .env with all required secrets
#   5. Configures LiveKit with server's public IP
#   6. Builds and starts everything
# ──────────────────────────────────────────────────────────

set -e

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║         🎓 TeachHub Deployment Script        ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Must run as root ────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root: sudo bash deploy.sh"
  exit 1
fi

# ─── Detect server public IP ────────────────────────────
SERVER_IP=$(curl -s4 ifconfig.me || curl -s4 icanhazip.com)
echo "🌐 Detected server IP: $SERVER_IP"

# ─── Ask for passwords or generate them ─────────────────
echo ""
read -p "Admin (teacher) password [auto-generate]: " ADMIN_PASS
if [ -z "$ADMIN_PASS" ]; then
  ADMIN_PASS=$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)
  echo "   Generated: $ADMIN_PASS"
fi

read -p "Platform owner password [auto-generate]: " PLATFORM_PASS
if [ -z "$PLATFORM_PASS" ]; then
  PLATFORM_PASS=$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)
  echo "   Generated: $PLATFORM_PASS"
fi

# Auto-generate internal secrets (users never see these)
SESSION_SECRET=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
LIVEKIT_SECRET=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

echo ""
echo "🔑 Secrets generated."

# ─── Install Docker ──────────────────────────────────────
if ! command -v docker &> /dev/null; then
  echo ""
  echo "📦 Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  echo "✅ Docker installed."
else
  echo "✅ Docker already installed."
fi

# ─── Firewall ────────────────────────────────────────────
echo ""
echo "🔒 Configuring firewall..."
apt-get install -y -qq ufw
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp    comment 'SSH'
ufw allow 80/tcp    comment 'HTTP'
ufw allow 443/tcp   comment 'HTTPS'
ufw allow 7881/tcp  comment 'LiveKit TCP'
ufw allow 7882:7892/udp comment 'LiveKit UDP/WebRTC'
ufw --force enable
echo "✅ Firewall configured."

# ─── Clone or update repo ───────────────────────────────
APP_DIR="/opt/teachhub"

if [ -d "$APP_DIR" ]; then
  echo ""
  echo "📁 Updating existing installation..."
  cd "$APP_DIR"
  git pull
else
  echo ""
  read -p "📁 Git repo URL (e.g. https://github.com/user/teachhub.git): " REPO_URL
  if [ -z "$REPO_URL" ]; then
    echo "❌ No repo URL provided. If you copied files manually, put them in $APP_DIR"
    mkdir -p "$APP_DIR"
    echo "   Then re-run this script."
    exit 1
  fi
  git clone "$REPO_URL" "$APP_DIR"
  cd "$APP_DIR"
fi

# ─── Create .env ─────────────────────────────────────────
echo ""
echo "📝 Writing .env..."
cat > "$APP_DIR/.env" << EOF
# ─── TeachHub Production Environment ────────────────────
# Auto-generated by deploy.sh on $(date)
# SAVE THESE CREDENTIALS SOMEWHERE SAFE!

SESSION_SECRET=$SESSION_SECRET
DB_PASSWORD=$DB_PASSWORD
LIVEKIT_API_SECRET=$LIVEKIT_SECRET

ADMIN_USER=admin
ADMIN_PASS=$ADMIN_PASS

PLATFORM_USER=owner
PLATFORM_PASS=$PLATFORM_PASS

BASE_URL=http://$SERVER_IP
PLATFORM_PATH=/ctrl-p-8x3kf

ANTHROPIC_API_KEY=
EOF
chmod 600 "$APP_DIR/.env"
echo "✅ .env created."

# ─── Configure LiveKit with real IP ──────────────────────
echo ""
echo "🎥 Configuring LiveKit for IP: $SERVER_IP..."
sed -i "s/NODE_IP/$SERVER_IP/g" "$APP_DIR/livekit-prod.yaml"
sed -i "s/LIVEKIT_SECRET/$LIVEKIT_SECRET/g" "$APP_DIR/livekit-prod.yaml"
echo "✅ LiveKit configured."

# ─── Build and start ─────────────────────────────────────
echo ""
echo "🚀 Building and starting TeachHub..."
cd "$APP_DIR"
docker compose -f docker-compose.prod.yml up -d --build

# ─── Wait for health ─────────────────────────────────────
echo ""
echo "⏳ Waiting for services to start..."
sleep 15

# Check health
if curl -sf http://localhost:80/ > /dev/null 2>&1; then
  echo "✅ TeachHub is running!"
else
  echo "⚠️  App may still be starting. Check: docker compose -f docker-compose.prod.yml logs app"
fi

# ─── Print summary ───────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              🎓 TeachHub is deployed!                ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  🌐 App:       http://$SERVER_IP"
echo "║  👨‍🏫 Teacher:   http://$SERVER_IP/admin/login"
echo "║  🔧 Platform:  http://$SERVER_IP/ctrl-p-8x3kf/login"
echo "║  📝 Apply:     http://$SERVER_IP/apply"
echo "║                                                      ║"
echo "║  Teacher login:   admin / $ADMIN_PASS"
echo "║  Platform login:  owner / $PLATFORM_PASS"
echo "║                                                      ║"
echo "║  ⚠️  SAVE THESE CREDENTIALS NOW!                     ║"
echo "║                                                      ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Useful commands:                                    ║"
echo "║  cd /opt/teachhub                                    ║"
echo "║  docker compose -f docker-compose.prod.yml logs -f   ║"
echo "║  docker compose -f docker-compose.prod.yml restart   ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
